### ISSUE TITLE
[FEAT] 인트로

### ISSUE THREAD

**Issue by 122nd** [PNU-DT-2023/InvitationToRemininsce#10]
### Feature
봉투 대기 상태에서 터치(클릭) → 봉투 열리고 퍼즐판과 퍼즐 조각 나오는 애니메이션 반영

### Tasks
- [x] hover로 봉투 열고 초대장 보여주기
- [x] 봉투 열 때 hover가 아닌 click으로 변경
- [ ] 봉투 열 때 퍼즐 조각 나오게 하기
- [ ] 퍼즐 조각 나올 때 초대장이 퍼즐판으로 바뀌게 하기

### References
https://www.youtube.com/watch?v=OAqaDHXgVCc
