### ISSUE TITLE
[FEAT] 엔딩 화면 

### ISSUE THREAD

**Issue by jinccc97** [PNU-DT-2023/InvitationToRemininsce#12]
## Description
디자인 된 버전으로 엔딩 화면을 개발합니다.
## Tasks
- [x] 엔딩 화면 디자인 진행
- [x] 팝업 화면 
- [x] 감상모드 전환
- [x] 홈으로 이동 기능
- [x] (optional) 감상모드 업그레이드 버전
## References
- 감상 시 로드뷰처럼 되게 하는 기능을 논의했었는데요, 파노라마 뷰어 기능을 활용하면 될 것 같아요.
블렌더에서 파노라마뷰를 렌더시킨 뒤,[링크](https://threejs.org/examples/?q=pano#webgl_panorama_equirectangular)를 참고해 만들어볼 생각입니다!
6개 뷰를 짤라서 하면 좀 어색한 느낌이더라구욧..
