### ISSUE TITLE
[FEAT] 퍼즐 인터랙션 기능

### ISSUE THREAD

**Issue by sorimchuku** [PNU-DT-2023/InvitationToRemininsce#3]
## Description
퍼즐의 모든것 입니다
## Tasks
- [x] 퍼즐 배경이미지 띄우기
- [x] 퍼즐조각 무작위 배치
- [x] 퍼즐조각 드래그
- [x] 퍼즐조각이 올바른 위치에만 스냅 (배경이미지와 맞는 위치)
- [x] (가능하다면) 이미 맞춘 퍼즐 다른곳으로 드래그 불가
- [x] 퍼즐 완성시 완성메시지(다음페이지 연계)
## References
- [LinkText](LinkAddress)

**Comment by jinccc97** [comment]
## QA 
06.25 (일)
### 수정사항
- [x] 스냅기능 타 브라우저 작동안됨
- [x] 스냅 시 연출효과 : 아웃라인 사라지게 (페이드아웃)
### 추가 개선
- [ ] 퍼즐 모양 (개인적) 연구

**Comment by jinccc97** [comment]
아이패드에서 조작해야하므로 touch 이벤트에 대해서도 대응이 필요합니다! 
mousemove 외에 touch에도 대응할 수 있도록 해주세요
- [x] touch 이벤트 추가
